---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: development
  name: consul8s
spec:
  replicas: 1
  selector:
    app: consul8s
  template:
    metadata:
      labels:
        app: consul8s
    spec:
      containers:
        - name: consul8s
          command: ["/usr/local/bin/consul8s", "--namespace", "development"]
          image: quay.io/reactiveops/consul8s:master
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
